# Needed for python 3.7+
dist: bionic

language: python

cache: pip

python:
  - '3.6'
  - '3.7'
  - '3.8'

before_install:
  - pip install -U pip 
  - pip install -U pytest 

install:
  - pip install 'urllib3<1.27,>=1.25.4'
  - pip install jinja2 MarkupSafe parameterized pyparsing pycodestyle pytest-xdist pyyaml 'six>=1.12'

# Build against 2.9 for now.  2.10 fails due to removal of ipaddress to ansible.network
script:
  - 'git clone --branch stable-2.9 --single-branch https://github.com/ansible/ansible.git'
  - . ansible/hacking/env-setup
  - ./misc/local2ansible
  - cd ansible
  - ansible-test sanity --requirements --python $TRAVIS_PYTHON_VERSION pfsense_.*
  - ansible-test units --requirements --python $TRAVIS_PYTHON_VERSION pfsense_.*
